STOP_WORDS = {
    'a', 'an', 'the', 'is', 'are', 'was', 'were', 'be', 'been', 'being',
    'have', 'has', 'had', 'do', 'does', 'did', 'and', 'but', 'if', 'or',
    'as', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between',
    'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to',
    'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again',
    'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how',
    'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some',
    'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too',
    'very', 's', 't', 'can', 'will', 'just', 'don', 'should', 'now', 'it',
    'its', 'itself', 'we', 'our', 'ours', 'ourselves', 'you', 'your', 'yours',
    'he', 'him', 'his', 'himself', 'she', 'her', 'hers', 'herself', 'they',
    'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom',
    'this', 'that', 'these', 'those', 'am',

    # Academic & Scientific Jargon
    'abstract', 'introduction', 'background', 'methods', 'method', 'methodology',
    'results', 'result', 'conclusion', 'conclusions', 'discussion', 'summary',
    'study', 'studies', 'research', 'analysis', 'analyses', 'data', 'dataset',
    'datasets', 'evidence', 'findings', 'finding', 'implications', 'implication',
    'application', 'applications', 'purpose', 'objective', 'objectives', 'aim',
    'aims', 'scope', 'limitation', 'limitations', 'future work', 'acknowledgments',
    'references', 'figure', 'figures', 'fig', 'table', 'tables', 'author', 'authors',
    'et al', 'publication', 'paper', 'article', 'review', 'case', 'report',
    'case report', 'case series', 'cohort', 'manuscript',

    # Common Verbs
    'using', 'showed', 'found', 'demonstrated', 'observed', 'investigated',
    'described', 'reported', 'suggested', 'analyzed', 'compared', 'identified',
    'characterized', 'evaluated', 'developed', 'performed', 'confirmed',
    'increase', 'decrease', 'increasing', 'decreasing', 'based', 'associated',
    'related', 'involved', 'including', 'following', 'comprising',

    # Common Adjectives/Adverbs
    'significant', 'significantly', 'novel', 'new', 'respective', 'respectively',
    'various', 'multiple', 'several', 'diverse', 'certain', 'specific',
    'different', 'potential', 'further', 'additional', 'recent', 'recently',
    'high', 'low', 'higher', 'lower', 'large', 'small', 'major', 'minor',
    'important', 'key', 'pivotal', 'crucial', 'main', 'primary', 'secondary',
    'good', 'better', 'best', 'well', 'poor', 'common', 'rare', 'current',
    'first', 'second', 'third', 'i', 'ii', 'iii', 'iv', 'v', 'c', 'e', 'g',

    # Generic Biomedical / Scientific Concepts
    'role', 'roles', 'impact', 'impacts', 'effect', 'effects', 'function', 'functions',
    'mechanism', 'mechanisms', 'pathway', 'pathways', 'process', 'processes',
    'system', 'systems', 'complex', 'complexes', 'factor', 'factors', 'activity',
    'activities', 'level', 'levels', 'patient', 'patients', 'individual', 'individuals',
    'human', 'humans', 'animal', 'animals', 'mouse', 'mice', 'rat', 'rats',
    'group', 'groups', 'sample', 'samples', 'tissue', 'tissues', 'cell', 'cells',
    'expression', 'regulation', 'upregulation', 'downregulation', 'production',
    'response', 'responses', 'association', 'correlation', 'relationship',
    'interaction', 'interactions', 'development', 'progression', 'proliferation',
    'metastasis', 'disease', 'diseases', 'disorder', 'disorders', 'syndrome',
    'condition', 'cancer', 'cancers', 'tumor', 'tumors', 'therapy', 'therapies',
    'treatment', 'treatments', 'therapeutic', 'drug', 'drugs', 'target', 'targets',
    'molecule', 'molecules', 'protein', 'proteins', 'gene', 'genes', 'rna', 'dna',
    'noncoding rna', 'noncoding rnas', 'coding', 'non-coding', 'region', 'regions',
    'domain', 'domains', 'family', 'families', 'type', 'types', 'class', 'classification',
    'number', 'values', 'value', 'field', 'area', 'information', 'knowledge',
    'understanding', 'approach', 'strategy', 'strategies', 'tool', 'tools',
    'platform', 'technology', 'characteristic', 'characteristics', 'feature', 'features',
    'property', 'properties', 'context', 'context', 'issue', 'issues', 'challenge',
    'challenges', 'need', 'presence', 'absence', 'change', 'changes', 'percent',
    'rate', 'rates', 'risk', 'risks', 'factor', 'factors', 'a key', 'a pivotal role',
    'a major', 'a significant', 'a combination', 'our understanding', 'a new',
    'these findings', 'our findings', 'this study', 'recent studies', 'a leading cause',
    'growing evidence', 'recent research',
}
SIGNIFICANT_LABELS = {
    "GENE_OR_GENE_PRODUCT",
    "AMINO_ACID",
    "CELL",
    "CELLULAR_COMPONENT",
    "CANCER",
    "TISSUE",
    "ORGAN",
    "PATHOLOGICAL_FORMATION",
    "SIMPLE_CHEMICAL",
    "ORGANISM"
}